name: Build NetHunter Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update

          sudo apt install -y \
            bc \
            bison \
            build-essential \
            flex \
            curl \
            zip \
            unzip \
            git \
            make \
            python3 \
            ccache \
            libssl-dev \
            libc6-dev \
            libelf-dev \
            gcc \
            g++ \
            clang \
            lld \
            llvm \
            binutils \
            gcc-aarch64-linux-gnu \
            gcc-arm-linux-gnueabi

      - name: Clone Proton Clang
        run: |
          git clone --depth=1 https://github.com/kdrag0n/proton-clang.git clang

      - name: Build Kernel
        run: |
          export ARCH=arm64
          export SUBARCH=arm64
          export KBUILD_BUILD_USER=github
          export KBUILD_BUILD_HOST=actions

          mkdir -p out

          make O=out nethunter_defconfig

          PATH=$PWD/clang/bin:$PATH \
          make -j$(nproc --all) \
            O=out \
            CC=clang \
            HOSTCC=gcc \
            HOSTCXX=g++ \
            HOSTLD=ld.lld \
            LD=ld.lld \
            AR=llvm-ar \
            NM=llvm-nm \
            OBJCOPY=llvm-objcopy \
            OBJDUMP=llvm-objdump \
            STRIP=llvm-strip \
            CROSS_COMPILE=aarch64-linux-gnu- \
            CROSS_COMPILE_ARM32=arm-linux-gnueabi-

      - name: Upload Kernel
        uses: actions/upload-artifact@v4
        with:
          name: ginkgoa16-kernel
          path: |
            out/arch/arm64/boot/Image.gz-dtb
            out/arch/arm64/boot/Image
