name: Build NetHunter Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update

          sudo apt install -y \
            bc \
            bison \
            build-essential \
            flex \
            curl \
            wget \
            zip \
            unzip \
            git \
            make \
            python3 \
            ccache \
            libssl-dev \
            libc6-dev \
            libelf-dev \
            gcc-aarch64-linux-gnu \
            gcc-arm-linux-gnueabi \
            clang \
            lld \
            llvm

      - name: Clean Source
        run: |
          rm -rf out
          make mrproper

      - name: Build Kernel
        run: |
          export ARCH=arm64
          export SUBARCH=arm64

          export KBUILD_BUILD_USER=github
          export KBUILD_BUILD_HOST=actions

          mkdir -p out

          make O=out nethunter_defconfig

          make -j$(nproc --all) \
            O=out \
            CC=clang \
            HOSTCC=gcc \
            HOSTCXX=g++ \
            LLVM=1 \
            LLVM_IAS=1 \
            CROSS_COMPILE=aarch64-linux-gnu- \
            CROSS_COMPILE_ARM32=arm-linux-gnueabi-

      - name: Upload Kernel
        uses: actions/upload-artifact@v4

        with:
          name: ginkgoa16-kernel

          path: |
            out/arch/arm64/boot/Image
            out/arch/arm64/boot/Image.gz-dtb
            out/arch/arm64/boot/dtbo.img
